apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 5
  template:
    metadata: #Definindo os metadados (Informações)
      labels: #Definindo Etiqueta
        app: "goserver"#Definindo qual é a etiqueta do pod
    spec: #Definindo a contstrução do pod
      containers: #Container
        - name: "goserver"
          image: "gabrielrodriguesdev/salve-go:latest" 